export enum ValidationCode {
  EMAIL_REQUIRED = 'EMAIL_REQUIRED',
  EMAIL_INVALID = 'EMAIL_INVALID',

  PASSWORD_REQUIRED = 'PASSWORD_REQUIRED',
  PASSWORD_WEAK = 'PASSWORD_WEAK',

  VALIDATION_UNKNOWN = 'VALIDATION_UNKNOWN',
}
