export enum ValidationCode {
  EMAIL_REQUIRED = 'EMAIL_REQUIRED',
  EMAIL_INVALID = 'EMAIL_INVALID',

  PASSWORD_REQUIRED = 'PASSWORD_REQUIRED',
  PASSWORD_WEAK = 'PASSWORD_WEAK',

  NAME_REQUIRED = 'NAME_REQUIRED',
  NAME_INVALID = 'NAME_INVALID',
  DESCRIPTION_INVALID = 'DESCRIPTION_INVALID',

  VALIDATION_UNKNOWN = 'VALIDATION_UNKNOWN',
}
