export enum ValidationCode {
  EMAIL_REQUIRED = 'EMAIL_REQUIRED',
  EMAIL_INVALID = 'EMAIL_INVALID',

  PASSWORD_REQUIRED = 'PASSWORD_REQUIRED',
  PASSWORD_WEAK = 'PASSWORD_WEAK',

  NAME_REQUIRED = 'NAME_REQUIRED',
  NAME_INVALID = 'NAME_INVALID',
  DESCRIPTION_INVALID = 'DESCRIPTION_INVALID',

  TITLE_REQUIRED = 'TITLE_REQUIRED',
  TITLE_INVALID = 'TITLE_INVALID',
  CONTENT_REQUIRED = 'CONTENT_REQUIRED',
  CONTENT_INVALID = 'CONTENT_INVALID',
  STATUS_REQUIRED = 'STATUS_REQUIRED',
  STATUS_INVALID = 'STATUS_INVALID',
  CATEGORY_ID_REQUIRED = 'CATEGORY_ID_REQUIRED',
  CATEGORY_ID_INVALID = 'CATEGORY_ID_INVALID',

  VALIDATION_UNKNOWN = 'VALIDATION_UNKNOWN',
}
